### PR TITLE
Use GitHub Actions to build Meteor Mongo

### PR DESCRIPTION
**Pull request by wreiske**
This commit replaces the Docker build code to build mongo using GitHub actions.

### CODE REVIEW

**Comment by klaussner** [comment]
Thanks for the PR, @wreiske. Is it possible to use CentOS 7 instead of Ubuntu to run the GitHub Action? We need to use CentOS 7 or something similar to increase compatibilty with older operating systems (e.g., https://github.com/meteor/meteor/issues/11004).

**Comment by wreiske** [comment]
> Thanks for the PR, @wreiske. Is it possible to use CentOS 7 instead of Ubuntu to run the GitHub Action? We need to use CentOS 7 or something similar to increase compatibility with older operating systems (e.g., [meteor/meteor#11004](https://github.com/meteor/meteor/issues/11004)).

GitHub's actions don't support CentOS 7 sadly. It does support mac-os or ubuntu. I was having issues compiling the latest MongoDB on anything lower than gcc8, so it may become an issue whereas we bump mongo versions server owners will need to stay up-to-date with the newer libraries. 

```
CentOS 6
./mongod
./mongod: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./mongod)
./mongod: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./mongod)
```

```
CentOS 7
./mongod
./mongod: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./mongod)
```

I can try building with an older version of GCC and seeing if that helps.

**Comment by wreiske** [comment]
@klaussner 
```
Mkdir("build/scons")
scons version: 3.0.4
python version: 3 6 9 'final' 0
CC is gcc-4.8
gcc-4.8 found in $PATH at /usr/bin/gcc-4.8
CXX is g++-4.8
g++-4.8 found in $PATH at /usr/bin/g++-4.8
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking that the C++ compiler can link a C++ program... yes
Checking if C++ compiler "g++-4.8" is GCC... yes
Checking if C compiler "gcc-4.8" is GCC... yes
Detected a x86_64 processor
Checking if target OS linux is supported by the toolchain... yes
Checking if C compiler is GCC 8.2 or newer...no
Checking if C++ compiler is GCC 8.2 or newer...no
ERROR: Refusing to build with compiler that does not meet requirements
See /home/runner/work/mongodb-builder/mongodb-builder/mongodb-src-r4.2.8/build/scons/config.log for details
##[error]Process completed with exit code 1.
```
I think we are going to be limited either way if we want to build 4.2.8. Thoughts?

**Comment by wreiske** [comment]
After ignoring the minimum requirements, it errors out still.

```Checking if we are using libstdc++... yes
Checking if C++ compiler supports -std=c++17... no
Compiler does not honor -std=c++17
See /home/runner/work/mongodb-builder/mongodb-builder/mongodb-src-r4.2.8/build/scons/config.log for details
##[error]Process completed with exit code 1.
```

I think if we want to get to mongo 4.2.8, we're going to have to use a newer GCC.

**Comment by klaussner** [comment]
Can we run the CentOS-based Docker container in the GitHub Action instead of using GCC on the native OS?

**Comment by wreiske** [comment]
> Can we run the CentOS-based Docker container in the GitHub Action instead of using GCC on the native OS?

Yes, but I don't know if that will help since the newer version of MongoDB probably won't build on it without including devtools-8 and compiling with a newer GCC that won't be available on older installations.

**Comment by klaussner** [comment]
I think it should work because GCC 8 is [installed in the container](https://github.com/meteor/mongodb-builder/blob/c82e7d159d54245fe114d75770e6736e6c9545f3/Dockerfile#L4) and links to the (old) version of glibc that is installed on CentOS 7.

**Comment by klaussner** [comment]
Why did you merge this, @filipenevola? 🙂 Building MongoDB on Ubuntu in a GitHub Action will lead to regressions like this: https://github.com/meteor/meteor/issues/11004.

**Comment by wreiske** [comment]
I am going to try and get the docker image building from the github action just in case. Ill open another PR sometime this weekend.

**Comment by wreiske** [comment]
@filipenevola I am worried this may cause issues and should be addressed before the next meteor release. If we can get the github action to run the docker in time, it may not matter, but I was not able to find the time to work on it.

**Comment by filipenevola** [comment]
My bad @klaussner, I don't know how I didn't see your message, I'll work on this.

**Comment by filipenevola** [comment]
Hi @klaussner the docker commands are working again but the new MongoDB is not compiling in that environment.

[See the logs](https://github.com/meteor/mongodb-builder/files/5070225/logs.txt)

I'm not sure if this version will compile on that version of CentOS / GCC.

Any ideas?

**Comment by renanccastro** [comment]
Hello, guys. I ran the docker build and compiled the files with centos 7.
Also updated the release on this repo with the new binaries. We should be good to go.

**Comment by renanccastro** [comment]
I forgot to mention, but I will undo this merge for now because of what was discussed above. But would be awesome if @wreiske could get centos docker running on Github actions, we would surely merge. I also had to run docker with more memory passing --memory=, in case you stumble with building errors.

**Comment by wreiske** [comment]
Noted! I'll see what I can do.

**Pull request merged**
